import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarMagic from "./_components/navbar/NavbarMagic";
import ProviderFarmer from "./_components/ProviderFarmer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
        <main  className="w-[90%] mx-auto ">
          <ProviderFarmer>
          {children}
          </ProviderFarmer>
        </main>
        <NavbarMagic  />
      </body>
    </html>
  );
}
